name: Bug Report
description: Report a bug in the project
type: Bug
projects: ["d0kima/1"]
body:
  - type: markdown
    attributes:
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is.

  - type: input
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: A clear and concise list of steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

  - type: input
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: A clear and concise description of what you expected to happen.

  - type: input
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: A clear and concise description of what actually happened.

  - type: input
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: If applicable, add screenshots to help explain your problem.

